### ISSUE TITLE
Returns with Not Found for no reason

### ISSUE THREAD

**Issue by raluvy95** [TeeSeal/discord.js-docs-api#5]
I'm using this api for my discord bot. I was testing if it works, but when I used the example `<url.com>/main/stable/embed?q=message%23pin` it returns with Not Found even when I changed to `?q=Client`.

help me

**Comment by TeeSeal** [comment]
Hey man, the documentation is outdated and I couldn't be arsed to update it. Sorry 😅

I didn't know people beside me used this. I'll look into updating the README today.

**Comment by TeeSeal** [comment]
Hey @raluvy95 I've updated the README to actually match the implementation. See it at https://github.com/TeeSeal/discord.js-docs-api/blob/master/README.md
